# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding rows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [2]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [3]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [4]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint:** You can also use **np.identity()** function ]

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.array()** function



In [10]:
d1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
d1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### Question 3

Interchange both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [11]:
d1.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [12]:
d1 +1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [19]:
nd6 = np.matrix([[ 1, 4, 9, 121, 144, 169], [ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])
nd6.mean()

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [22]:
print(d1)
print(nd6)
np.dot(d1,nd6)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]


matrix([[ 480,  684,  936, 4680, 5364, 6096],
        [ 282,  405,  558, 2862, 3285, 3738],
        [  84,  126,  180, 1044, 1206, 1380]])

### Array Slicing/Indexing:

- Now we'll learn to access multiple elements or a range of elements from an array.

In [25]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Question 8

Print the array elements from start to 4th position


In [27]:
print(x[:5])

[0 1 2 3 4]


In [36]:
x[0:5:]

array([0, 1, 2, 3, 4])

### Question 9

- Return elements from first position with step size 2. (Difference between consecutive elements is 2)

In [29]:
print(x[1::2])

[ 1  3  5  7  9 11 13 15 17 19]


### Question 10

Reverse the array using array indexing:

In [32]:
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])